import { Router } from "express";
import newMazeRouter from "../../src/routes/maze.routes";
import { containerMock, mazeControllerMock } from "./mocks";

describe("MazeRoutes", () => {
  const controller = mazeControllerMock();
  const container = containerMock(controller);
  const router = Router();
  jest.spyOn(router, "post");
  jest.spyOn(router, "get");

  newMazeRouter(router, container);

  it("should have the routes defined with the correct methods and pointing the correct controller method", () => {
    expect(router.post).toHaveBeenNthCalledWith(1, "/maze", controller.create);
    expect(router.post).toHaveBeenNthCalledWith(
      2,
      "/maze/autogenerate",
      controller.createAutogenerated
    );
    expect(router.post).toHaveBeenNthCalledWith(
      3,
      "/maze/:id/solve",
      controller.solve
    );
    expect(router.get).toHaveBeenNthCalledWith(1, "/maze/:id", controller.get);
  });
});
